import type { ServiceItem, ServiceModule } from "./types";

export const DEFAULT_PINNED_IDS = [
  "att-checkin",
  "hr-calendar",
  "pay-slips",
  "op-inventory",
];

export const LUXCARE_MODULES: ServiceModule[] = [
  {
    id: "popular",
    title: "Dịch vụ phổ biến",
    shortTitle: "Phổ biến",
    items: [
      {
        id: "pop-checkin",
        title: "Chấm công\n& Ca trực",
        icon: "time",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/attendance",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-calendar",
        title: "Lịch làm việc",
        icon: "calendar",
        color: "#0d9488",
        bgColor: "#f0fdfa",
        route: "/(tabs)/calendar-events",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-work",
        title: "Công việc\ncần làm",
        icon: "checkbox",
        color: "#2563eb",
        bgColor: "#eff6ff",
        route: "/(tabs)/work",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-payslip",
        title: "Bảng lương",
        icon: "wallet",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/payslips",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-inventory",
        title: "Vật tư\n& Dược phẩm",
        icon: "cube",
        color: "#10b981",
        bgColor: "#ecfdf5",
        route: "/(tabs)/inventory",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-equipment",
        title: "Thiết bị\ny tế",
        icon: "medkit",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/equipment",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-chat",
        title: "Trò chuyện\nnội bộ",
        icon: "chatbubble-ellipses",
        color: "#0d9488",
        bgColor: "#f0fdfa",
        route: "/(tabs)/chat",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-directory",
        title: "Danh bạ\nnhân viên",
        icon: "people",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/employees",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-crm",
        title: "Khách hàng\n& Leads",
        icon: "people",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/customers",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-users",
        title: "Quản lý\nngười dùng",
        icon: "people-circle",
        color: "#6366f1",
        bgColor: "#eef2ff",
        route: "/(tabs)/users",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-blog",
        title: "Bảng tin\ndoanh nghiệp",
        icon: "newspaper",
        color: "#ea580c",
        bgColor: "#fff7ed",
        route: "/(tabs)/blog",
        moduleId: "popular",
        status: "active",
      },
      {
        id: "pop-workflow",
        title: "Quy trình\nlàm việc",
        icon: "git-merge",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/workflow",
        moduleId: "popular",
        status: "active",
      },
    ],
  },
  {
    id: "hr",
    title: "Nhân sự & Chấm công",
    shortTitle: "Nhân sự & Chấm công",
    items: [
      {
        id: "att-checkin",
        title: "Chấm công\nhôm nay",
        icon: "finger-print",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/attendance",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "att-mgmt",
        title: "Quản lý\n& Duyệt công",
        icon: "calendar-clear",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/attendance-management",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-calendar",
        title: "Lịch làm việc",
        icon: "calendar",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/calendar-events",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "pay-slips",
        title: "Bảng lương",
        icon: "wallet",
        color: "#10b981",
        bgColor: "#ecfdf5",
        route: "/(tabs)/payslips",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-directory",
        title: "Danh bạ\nnhân sự",
        icon: "people",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/employees",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-orgchart",
        title: "Sơ đồ\ntổ chức",
        icon: "git-network",
        color: "#6366f1",
        bgColor: "#eef2ff",
        route: "/(tabs)/org-chart",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-workflow",
        title: "Quy trình\nlàm việc",
        icon: "git-merge",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/workflow",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-pipeline",
        title: "Quy trình\ntuyển dụng",
        icon: "git-branch",
        color: "#f59e0b",
        bgColor: "#fffbeb",
        route: "/(tabs)/recruitment-pipeline",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-contracts",
        title: "Hợp đồng\nlao động",
        icon: "newspaper",
        color: "#047857",
        bgColor: "#ecfdf5",
        route: "/(tabs)/contracts",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-credentials",
        title: "Văn bằng\nchứng chỉ",
        icon: "ribbon",
        color: "#d97706",
        bgColor: "#fffbeb",
        route: "/(tabs)/credentials",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "hr-training",
        title: "Đào tạo\nNội bộ",
        icon: "school",
        color: "#7c3aed",
        bgColor: "#f5f3ff",
        route: "/(tabs)/training",
        moduleId: "hr",
        status: "active",
      },
      {
        id: "rec-recruitment",
        title: "Tuyển dụng",
        icon: "megaphone",
        color: "#ea580c",
        bgColor: "#fff7ed",
        route: "/(tabs)/recruitment",
        moduleId: "hr",
        status: "active",
      },
    ],
  },
  {
    id: "operations",
    title: "Vận hành & Y tế",
    shortTitle: "Vận hành & Y tế",
    items: [
      {
        id: "op-inventory",
        title: "Vật tư\n& Dược phẩm",
        icon: "cube",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/inventory",
        moduleId: "operations",
        status: "active",
      },
      {
        id: "op-stock",
        title: "Xuất - Nhập\nTồn kho",
        icon: "swap-vertical",
        color: "#0d9488",
        bgColor: "#f0fdfa",
        route: "/(tabs)/inventory-stock",
        moduleId: "operations",
        status: "coming_soon",
      },
      {
        id: "op-expiry",
        title: "Cảnh báo\nhạn sử dụng",
        icon: "alert-circle",
        color: "#e11d48",
        bgColor: "#fff1f2",
        route: "/(tabs)/inventory-expiry",
        moduleId: "operations",
        status: "coming_soon",
      },
      {
        id: "op-audit",
        title: "Phiếu kiểm kê\nvật tư",
        icon: "clipboard",
        color: "#d97706",
        bgColor: "#fffbeb",
        route: "/(tabs)/inventory-audit",
        moduleId: "operations",
        status: "coming_soon",
      },
      {
        id: "op-equipment",
        title: "Quản lý\nthiết bị y tế",
        icon: "medkit",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/equipment",
        moduleId: "operations",
        status: "active",
      },
      {
        id: "op-maintenance",
        title: "Lịch bảo trì\nmáy móc",
        icon: "construct",
        color: "#2563eb",
        bgColor: "#eff6ff",
        route: "/(tabs)/equipment-maintenance",
        moduleId: "operations",
        status: "coming_soon",
      },
      {
        id: "op-repair",
        title: "Báo hỏng\nthiết bị",
        icon: "flash",
        color: "#ea580c",
        bgColor: "#fff7ed",
        route: "/(tabs)/equipment-repair",
        moduleId: "operations",
        status: "coming_soon",
      },
      {
        id: "op-crm",
        title: "Khách hàng\n& Tiếp nhận",
        icon: "people",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/customers",
        moduleId: "operations",
        status: "active",
      },
      {
        id: "op-leads",
        title: "Tiếp nhận\ntư vấn Leads",
        icon: "call",
        color: "#10b981",
        bgColor: "#ecfdf5",
        route: "/(tabs)/customers",
        moduleId: "operations",
        status: "active",
      },
      {
        id: "op-survey",
        title: "Khảo sát\nkhách hàng",
        icon: "reader",
        color: "#7c3aed",
        bgColor: "#f5f3ff",
        route: "/(tabs)/crm-survey",
        moduleId: "operations",
        status: "coming_soon",
      },
    ],
  },
  {
    id: "work",
    title: "Công việc",
    shortTitle: "Công việc",
    items: [
      {
        id: "work-my",
        title: "Công việc\ncủa tôi",
        icon: "checkmark-done-circle",
        color: "#2563eb",
        bgColor: "#eff6ff",
        route: "/(tabs)/work",
        moduleId: "work",
        status: "active",
      },
      {
        id: "work-kanban",
        title: "Bảng Kanban\ntiến độ",
        icon: "grid",
        color: "#0891b2",
        bgColor: "#ecfeff",
        route: "/(tabs)/work",
        moduleId: "work",
        status: "active",
      },
      {
        id: "work-kpi",
        title: "Báo cáo\nKPI tháng",
        icon: "trending-up",
        color: "#16a34a",
        bgColor: "#f0fdf4",
        route: "/(tabs)/kpi",
        moduleId: "work",
        status: "active",
      },
      {
        id: "work-calendar",
        title: "Lịch công việc\n& Deadline",
        icon: "calendar-number",
        color: "#f59e0b",
        bgColor: "#fffbeb",
        route: "/(tabs)/work-calendar",
        moduleId: "work",
        status: "active",
      },
      {
        id: "work-urgent",
        title: "Việc khẩn cấp\nquá hạn",
        icon: "alert-circle",
        color: "#dc2626",
        bgColor: "#fef2f2",
        route: "/(tabs)/work",
        moduleId: "work",
        status: "active",
      },
    ],
  },
  {
    id: "communication",
    title: "Truyền thông & Hệ thống",
    shortTitle: "Truyền thông & Hệ thống",
    items: [
      {
        id: "comm-chat",
        title: "Trò chuyện\nnội bộ",
        icon: "chatbubble-ellipses",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/chat",
        moduleId: "communication",
        status: "active",
      },
      {
        id: "comm-groups",
        title: "Nhóm\nphòng ban",
        icon: "chatbubbles",
        color: "#0284c7",
        bgColor: "#f0f9ff",
        route: "/(tabs)/chat",
        moduleId: "communication",
        status: "active",
      },
      {
        id: "comm-blog",
        title: "Bảng tin\nBlog nội bộ",
        icon: "newspaper",
        color: "#ea580c",
        bgColor: "#fff7ed",
        route: "/(tabs)/blog",
        moduleId: "communication",
        status: "active",
      },
      {
        id: "comm-broadcast",
        title: "Thông báo\ntoàn viện",
        icon: "megaphone",
        color: "#d97706",
        bgColor: "#fffbeb",
        route: "/(tabs)/notifications",
        moduleId: "communication",
        status: "active",
      },
      {
        id: "comm-knowledge",
        title: "Kho tri thức\n& SOP y tế",
        icon: "library",
        color: "#7c3aed",
        bgColor: "#f5f3ff",
        route: "/(tabs)/knowledge",
        moduleId: "communication",
        status: "coming_soon",
      },
      {
        id: "sys-users",
        title: "Quản lý\nngười dùng",
        icon: "people-circle",
        color: "#6366f1",
        bgColor: "#eef2ff",
        route: "/(tabs)/users",
        moduleId: "communication",
        status: "active",
      },
      {
        id: "sys-roles",
        title: "Phân quyền\n& Vai trò",
        icon: "shield-checkmark",
        color: "#059669",
        bgColor: "#ecfdf5",
        route: "/(tabs)/roles",
        moduleId: "communication",
        status: "coming_soon",
      },
      {
        id: "sys-settings",
        title: "Cài đặt\nhệ thống",
        icon: "settings",
        color: "#64748b",
        bgColor: "#f8fafc",
        route: "/(tabs)/settings",
        moduleId: "communication",
        status: "coming_soon",
      },
    ],
  },
];

export function getAllServicesFlat(modulesList = LUXCARE_MODULES): ServiceItem[] {
  const list: ServiceItem[] = [];
  const seen = new Set<string>();
  for (const mod of modulesList) {
    for (const item of mod.items) {
      if (!seen.has(item.id)) {
        seen.add(item.id);
        list.push(item);
      }
    }
  }
  return list;
}
